std = "lua51"
max_line_length = false
exclude_files = { ".release/" }

-- WoW calls script handlers with fixed argument lists, so unused arguments are expected.
unused_args = false

globals = {
    -- Saved variables and addon tables
    "BindPadVars",
    "BindPadCore",
    "BindPadL",
    "BindPadMacroPopupMixin",
    "BINDING_HEADER_BINDPAD",
    "BINDING_NAME_TOGGLE_BINDPAD",
    "SLASH_BINDPAD1",
    "SLASH_BINDPAD2",
    "SlashCmdList",
    "UIPanelWindows",

    -- Functions called from BindPad.xml, Bindings.xml and the TOC
    "BindPad_SlashCmd",
    "BindPadBindFrame_OnHide",
    "BindPadBindFrame_OnKeyDown",
    "BindPadBindFrame_Unbind",
    "BindPadBindFrame_Update",
    "BindPadCheckButton_SetLabel",
    "BindPadFrame_ChangeBindingProfile",
    "BindPadFrame_ForAllCharactersToggle",
    "BindPadFrame_OnEnter",
    "BindPadFrame_OnEvent",
    "BindPadFrame_OnHide",
    "BindPadFrame_OnLoad",
    "BindPadFrame_OnMouseDown",
    "BindPadFrame_OnShow",
    "BindPadFrame_OpenSpellBook",
    "BindPadFrame_OutputText",
    "BindPadFrame_SaveAllKeysToggle",
    "BindPadFrame_ShowHotkeyToggle",
    "BindPadFrame_Toggle",
    "BindPadFrameTab_OnClick",
    "BindPadFrameTab_OnEnter",
    "BindPadMacroAddButton_OnClick",
    "BindPadMacroDeleteButton_OnClick",
    "BindPadMacroFrame_OnHide",
    "BindPadMacroFrame_OnShow",
    "BindPadMacroFrame_Open",
    "BindPadMacroFrameEditButton_OnClick",
    "BindPadMacroPopupFrame_Open",
    "BindPadProfileTab_OnClick",
    "BindPadProfileTab_OnEnter",
    "BindPadProfileTab_OnShow",
    "BindPadShowLessSlotButton_OnClick",
    "BindPadShowMoreSlotButton_OnClick",
    "BindPadSlot_OnClick",
    "BindPadSlot_OnDragStart",
    "BindPadSlot_OnEnter",
    "BindPadSlot_OnReceiveDrag",
    "BindPadSlot_OnUpdateBindings",
    "BindPadSlot_UpdateState",

    -- Frames from BindPad.xml that get fields assigned
    "BindPadMacroPopupFrame",
}

read_globals = {
    table = { fields = { "wipe" } },

    -- Frames from BindPad.xml
    "BindPadBindFrame",
    "BindPadBindFrameAction",
    "BindPadBindFrameForAllCharacterButton",
    "BindPadBindFrameKey",
    "BindPadDialogFrame",
    "BindPadFrame",
    "BindPadFrameTab2",
    "BindPadKey",
    "BindPadMacro",
    "BindPadMacroFrame",
    "BindPadMacroFrameSlotButton",
    "BindPadMacroFrameSlotButtonIcon",
    "BindPadMacroFrameSlotName",
    "BindPadMacroFrameTestButton",
    "BindPadMacroFrameText",
    "BindPadRank",
    "BindPadScrollFrameNumber",
    "BindPadShowLessSlotButton",
    "BindPadSlotButtonContainer",

    -- WoW Lua aliases
    "floor",
    "format",
    "gsub",
    "max",
    "min",
    "mod",
    "strfind",
    "strlower",
    "strsub",

    -- WoW API
    "C_Container",
    "C_EquipmentSet",
    "C_Item",
    "C_MountJournal",
    "C_PetJournal",
    "C_SpecializationInfo",
    "C_Spell",
    "C_SpellBook",
    "C_Timer",
    "C_Traits",
    "ClearCursor",
    "CreateFrame",
    "GetActionInfo",
    "GetBinding",
    "GetBindingAction",
    "GetBindingFromClick",
    "GetBindingKey",
    "GetBindingText",
    "GetCurrentBindingSet",
    "GetCursorInfo",
    "GetCVarBool",
    "GetLocale",
    "GetMacroInfo",
    "GetMerchantItemLink",
    "GetNumBindings",
    "GetRealmName",
    "GetTime",
    "hooksecurefunc",
    "InCombatLockdown",
    "IsAltKeyDown",
    "IsControlKeyDown",
    "IsModifierKeyDown",
    "issecretvalue",
    "IsShiftKeyDown",
    "LoadBindings",
    "PickupMacro",
    "PlaySound",
    "ResetCursor",
    "RunBinding",
    "SaveBindings",
    "SetBinding",
    "SetCursor",
    "UnitClass",
    "UnitName",

    -- Blizzard UI (FrameXML and shared templates)
    "ActionBarButtonEventsFrame",
    "ChatEdit_InsertLink",
    "ChatFrame1",
    "ChatFrameUtil",
    "CreateAndInitFromMixin",
    "Enum",
    "GameFontHighlightSmall",
    "GameTooltip",
    "GameTooltip_AddNormalLine",
    "GameTooltip_Hide",
    "GameTooltip_SetTitle",
    "GenerateClosure",
    "GetUIPanelWidth",
    "HideUIPanel",
    "IconDataProviderExtraType",
    "IconDataProviderMixin",
    "IconSelectorPopupFrameIconFilterTypes",
    "IconSelectorPopupFrameTemplateMixin",
    "MacroFrameText",
    "MenuResponse",
    "MenuUtil",
    "NameUtil",
    "PanelTemplates_SetNumTabs",
    "PanelTemplates_SetTab",
    "PanelTemplates_TabResize",
    "PlayerSpellsUtil",
    "ShowUIPanel",
    "SOUNDKIT",

    -- Global strings
    "CHARACTER_SPECIFIC_KEYBINDING_TOOLTIP",
    "CONFIRM_DELETING_CHARACTER_SPECIFIC_BINDINGS",
    "DUAL_SPEC_PRIMARY",
    "DUAL_SPEC_SECONDARY",
    "FONT_COLOR_CODE_CLOSE",
    "ICON_SELECTION_CLICK",
    "NORMAL_FONT_COLOR_CODE",
    "PET_ACTION_ATTACK",
    "PET_ACTION_FOLLOW",
    "PET_ACTION_MOVE_TO",
    "PET_ACTION_WAIT",
    "PET_MODE_AGGRESSIVE",
    "PET_MODE_ASSIST",
    "PET_MODE_DEFENSIVE",
    "PET_MODE_PASSIVE",
    "SLASH_CAST1",
    "SLASH_CLICK1",
    "SLASH_EQUIP1",
    "SLASH_EQUIP_SET1",
    "SLASH_PET_AGGRESSIVE1",
    "SLASH_PET_ASSIST1",
    "SLASH_PET_ATTACK1",
    "SLASH_PET_DEFENSIVE1",
    "SLASH_PET_FOLLOW1",
    "SLASH_PET_MOVE_TO1",
    "SLASH_PET_PASSIVE1",
    "SLASH_PET_STAY1",
    "SLASH_SCRIPT1",
    "SLASH_SUMMON_BATTLE_PET1",
    "SLASH_USE1",
}
